### PR TITLE
refactor(wrapper.ts) format and style

### PR DESCRIPTION
**Pull request by PatrickJS**
fix spacing
`const` rather than `let`

redo types 
```typescript
const ref = this[NODE];
return signalGetFn.call<SignalNode<T>, [], T>(ref);
```
from 
```typescript
return signalGetFn<T>.call(this[NODE]);
```

probably better to review with split diff
https://github.com/proposal-signals/proposal-signals/pull/97/files?diff=split

### CODE REVIEW

**Comment by littledan** [comment]
If we’re making these style fixes, do you want to set this up with some config files/CI so it is more sustainable than manual application?

**Comment by PatrickJS** [comment]
yup I can set that up 👍 any preference? I'm thinking github actions eslint and prettier config

**Comment by littledan** [comment]
My main preference is, leave the files which are forked from Angular as they are format-wise, to make it easier to later synchronize with them. Other than that, as long as we have semicolons, I am good with whatever style choice.

**Comment by PatrickJS** [comment]
I'll get to this this weekend 👍

**Comment by PatrickJS** [comment]
closing for https://github.com/tc39/proposal-signals/pull/163

**Pull request closed without merging**
